# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vhparaujo
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aula5-clinica

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:*
          Resource: "*"

functions:
  patientsCreate:
    handler: src/patients/functions/create.handler
    events:
      - http:
          path: patients
          method: POST

  patientsFindById:
    handler: src/patients/functions/find.findByIdHandler
    events:
      - http:
          method: GET
          path: patients/{id}

  patientsFind:
    handler: src/patients/functions/find.findHandler
    events:
      - http:
          method: GET
          path: patients

  patientsPatch:
    handler: src/patients/functions/patch.handler
    events:
      - http:
          method: PATCH
          path: patients/{id}

  patientsRemove:
    handler: src/patients/functions/remove.handler
    events:
      - http:
          method: DELETE
          path: patients/{id}

resources:
  Resources:
    patientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Patient
        AttributeDefinitions:
          - AttributeName: PK #taxId
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
